

spring:
  application:
    name: SECURITY-SERVICE





eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  #    copic-account-service.herokuapp.com
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}






